language: generic
sudo: required

branches:
  only:
    - master

services:
  - docker

install: bash .travis/install.sh

env:
  - OCAML_VERSION=4.05.0          PROFILE="optimize"  MIN_REQS_ONLY="true"
  - OCAML_VERSION=4.05.0+flambda  PROFILE="optimize"  MIN_REQS_ONLY="true"
  - OCAML_VERSION=4.05.0          PROFILE="optimize"
  - OCAML_VERSION=4.05.0+flambda  PROFILE="optimize"
  - OCAML_VERSION=4.06.1          PROFILE="optimize"
  - OCAML_VERSION=4.06.1+flambda  PROFILE="optimize"
  - OCAML_VERSION=4.07.1          PROFILE="optimize"
  - OCAML_VERSION=4.07.1+flambda  PROFILE="optimize"
  - OCAML_VERSION=4.05.0          PROFILE="debug"
  - OCAML_VERSION=4.05.0+flambda  PROFILE="debug"
  - OCAML_VERSION=4.06.1          PROFILE="debug"
  - OCAML_VERSION=4.06.1+flambda  PROFILE="debug"
  - OCAML_VERSION=4.07.1          PROFILE="debug"
  - OCAML_VERSION=4.07.1+flambda  PROFILE="debug"

script: bash .travis/script.sh